// Generated by scripts/sync-google-drive-archive.mjs. Do not edit by hand.
export type SourceArchiveFile = {
  driveFileId: string;
  relation: "source-copy" | "related-material";
  mimeType: string;
  size: number;
};

export const sourceArchiveFiles = {
  "1681_Mariotte": {
    "driveFileId": "1EskyCLQ8c-cFoqLsgFsRhFyTWQZue3tf",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 27563146
  },
  "1767_Saussure": {
    "driveFileId": "1CUmnpAXLEyCO-R7ku1Im9LopfZFvhJRW",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 39474823
  },
  "1801_Herschel": {
    "driveFileId": "1zxzRhDP0btwuNJbHs_8T5w90_RA6X64j",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 9768235
  },
  "1804_Leslie": {
    "driveFileId": "1V56FWlRTsfzf8j9u3Gk9DXKjMD_Csh-C",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 44199739
  },
  "1824_Fourier": {
    "driveFileId": "12-cKSWYX0UJ4Gj-POaBW_r7UfYoIgBFH",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 88028800
  },
  "1840_Agassiz": {
    "driveFileId": "1dEjTGQCa8KF4BgnzZ9fv6egx5j_dFJgp",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 70480986
  },
  "1856_Foote": {
    "driveFileId": "1WPMm9i4NtBZp6FXIBDF5EeBbPePzbIwv",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 27445083
  },
  "1862_Tyndall": {
    "driveFileId": "1l0MpBqo_xA3mVdRJ7h3XS8maPZ_DPggs",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 4712619
  },
  "1864_Croll": {
    "driveFileId": "1bvHqB76e2CdgAFv8ZJdg4CoO5KzSyb5g",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 22878782
  },
  "1884_Langley": {
    "driveFileId": "11aIznPAcwBWNm8ayvEnqVqScmaQjaUna",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 15756165
  },
  "1894_Hogbom": {
    "driveFileId": "1MVynMn7UnM7h-bqQf8P_Fl-1h5CQwvcY",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 2435346
  },
  "1896_Arrhenius": {
    "driveFileId": "1BJeC3p3aw4BF8vY3tfQKw_5mC-9_IcEh",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 4518810
  },
  "1938_Callendar": {
    "driveFileId": "1s14Ife4-_s58dQqCf_zn7kukS0hUb5H_",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 1035783
  },
  "1941_Milankovic": {
    "driveFileId": "1vap1TERiywcc8CG_k4AUxqqljShMsKlF",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 42251942
  },
  "1952_Libby": {
    "driveFileId": "1lDMkyZVsEB9sCdNYiWVjg1wDY3tO4O9U",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 10284445
  },
  "1955_Emiliani": {
    "driveFileId": "10RRkDp57tk0N-IgerSjeQbHJyEdNvQ-_",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 4758658
  },
  "1956_Plass": {
    "driveFileId": "1JmsYBGlO4wsjVdhsPRXsQlnAG0SLia0A",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 2369267
  },
  "1990_IPCC_FAR": {
    "driveFileId": "1D_nNABKQ0_M2H1QCESrTSiS4qxEafRq_",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 15212975
  },
  "2000_Argo": {
    "driveFileId": "1qpVCoR693XfyfUdZmHiBkqnRpMayxp1T",
    "relation": "related-material",
    "mimeType": "application/pdf",
    "size": 2715713
  },
  "2014_BIPM_Thermistors": {
    "driveFileId": "1lQyGu93SI_lRm-PMPkGLL48MZl86WE6U",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 695076
  },
  "2021_BIPM_IPRT": {
    "driveFileId": "1i5FLbOVIBN_H253jPsB5fwTopnCHJRkI",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 1176720
  },
  "2021_BIPM_SPRT": {
    "driveFileId": "16WQJNZOD6kV7wnp3oERBn8SJzk0oky9T",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 1186535
  },
  "2025_USCRN_Blue_Hill": {
    "driveFileId": "1MANFaiQ9zKvszDCZYsT06mheMkqOUdlM",
    "relation": "source-copy",
    "mimeType": "text/plain",
    "size": 79205
  },
  "2026_SeaBird_SBE41": {
    "driveFileId": "1nXWDG5gObUJB7QuTQ2tsS-IoxfJWh7t1",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 185689
  },
  "2026_USCRN_Daily01_Readme": {
    "driveFileId": "1Eb-8hsbdnRcChP55qd1MtmbmCx98ZRiq",
    "relation": "source-copy",
    "mimeType": "text/plain",
    "size": 20377
  },
  "DOI_10_1002_2014gl061957": {
    "driveFileId": "1djiJQTWLVsr0BdBJKCIhjQzFkrd51gC9",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 808796
  },
  "DOI_10_1002_2015rg000502": {
    "driveFileId": "1XTrilcu0TzPVtAfND-MgqFG-n__FtHbZ",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 7931428
  },
  "DOI_10_1002_ecm_1552": {
    "driveFileId": "1-3WzRh-96FtjuQoJqqkxPW2rSf9mPvFZ",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 1128616
  },
  "DOI_10_1002_jgrd_50150": {
    "driveFileId": "1Xid3WpFyx6rA6g604j0lg7FjQV7xjYNH",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 7392691
  },
  "DOI_10_1002_joc_1594": {
    "driveFileId": "1f8QDoB1GIzj1GLZOVTbOIwpHemhitjgk",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 494617
  },
  "DOI_10_1002_joc_4775": {
    "driveFileId": "11ffG-tgSbTbs_g4k_rFjHCKaz6heRkJc",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 27893452
  },
  "DOI_10_1002_lno_12477": {
    "driveFileId": "1_lrgEdQbBESFCcHkKth0xXJNGDZhmt4M",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 1125833
  },
  "DOI_10_1007_s00484_014_0789_5": {
    "driveFileId": "1Bx3fU7fxS1zCTOFlzg2Hiyr1mk6eHTBg",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 745516
  },
  "DOI_10_1007_s00484_021_02185_y": {
    "driveFileId": "1fW2LQN_scGPvKC19nEukvEYCTP5lGeTK",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 1414859
  },
  "DOI_10_1007_s10712_011_9119_1": {
    "driveFileId": "1JbwVc_X6BzIVZpeaFiYKZoqRLkMUB8CU",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 2695052
  },
  "DOI_10_1007_s10712_019_09525_z": {
    "driveFileId": "1ZYkQ8vdl7Z6CYw7bfwiD0XUCZrLZU7M-",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 1255331
  },
  "DOI_10_1016_j_agrformet_2014_05_008": {
    "driveFileId": "1p2hnrbDYxDrIKfHcNxibpj_K-gaeT1HV",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 4523106
  },
  "DOI_10_1016_j_agrformet_2018_03_003": {
    "driveFileId": "1zFo-ypQVcnkqNfeU5AeX5F1DeSzl94Nq",
    "relation": "source-copy",
    "mimeType": "application/octet-stream",
    "size": 30738
  },
  "DOI_10_1016_j_marchem_2018_10_006": {
    "driveFileId": "1q98YHSIYoW7X2AWP4cDJBPFH0J4Lciry",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 1849574
  },
  "DOI_10_1017_jog_2019_66": {
    "driveFileId": "1427lRHUYoZKBLkZMPlrTgSUChlI5OoSp",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 1483913
  },
  "DOI_10_1029_2005jd006290": {
    "driveFileId": "1ZQpGLGob9BJ5pysoopoE8EEav_xa9Rw5",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 4210886
  },
  "DOI_10_1029_2005jd006548": {
    "driveFileId": "14V4OvNiziOCRWhNZ1Lneqcce2YDbgBg6",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 1771036
  },
  "DOI_10_1029_2008jd010421": {
    "driveFileId": "1UoOZfkGK-Ul0ZcOS5S2bQ0i2JqqAxznd",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 1141500
  },
  "DOI_10_1029_2012gl051106": {
    "driveFileId": "19U19sfvVDxMhQPhaIwbH_khVGLDvqJNy",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 6435819
  },
  "DOI_10_1029_2017jd028200": {
    "driveFileId": "1OAthfaWiMGtHNt94QJNnm_vVuHuKKUU9",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 5147431
  },
  "DOI_10_1029_2019jd032263": {
    "driveFileId": "1eBadqunzgeI0VxNIeHz9h_g6nUC692_-",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 1084496
  },
  "DOI_10_1029_2019jd032361": {
    "driveFileId": "1nCL5zJi6K7963H5kOZ-twDqzJ6_KIS8-",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 6238514
  },
  "DOI_10_1029_2023ea003279": {
    "driveFileId": "1tO9Yef7l9bppsX-RjJwFJKJEzMdXGMXj",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 2982729
  },
  "DOI_10_1029_2023gb007765": {
    "driveFileId": "1m19Mt1SeOy9iJ4iSLcII6sgMDsV_JhBT",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 11792251
  },
  "DOI_10_1029_2024gl111229": {
    "driveFileId": "1nBRiW5ghJ2g4yhsirE-TDfZ-TiGeAny6",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 2233898
  },
  "DOI_10_1038_s41467_018_08240_4": {
    "driveFileId": "1xv1zuYswzQrrRqBDKvMv0V_m20aoWc3f",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 6060543
  },
  "DOI_10_1038_s41467_022_31432_y": {
    "driveFileId": "1YHoIL9dZtV2R5OnGiCQvIGy-5aV_jPgb",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 2978403
  },
  "DOI_10_1038_s41467_023_42143_3": {
    "driveFileId": "11eJ7poWdVWsOpSOFrXwthDkoIbLj52fg",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 2634807
  },
  "DOI_10_1038_s41558_018_0245_3": {
    "driveFileId": "1Biws5jkJCUifVjPvTS9Gg-qzImYBLHlA",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 523934
  },
  "DOI_10_1038_s41586_018_0179_y": {
    "driveFileId": "1Z8Hc-SwArH8DSHw31yhWmG09PH_sLmod",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 5502846
  },
  "DOI_10_1038_s41586_019_1071_0": {
    "driveFileId": "1rAGM9hOSpQb0BMu3SXT4XE0_TMkNfXGB",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 398817
  },
  "DOI_10_1038_s41586_019_1855_2": {
    "driveFileId": "16cKFcPbMwYCGEYu6ZUCozTgjmxCFfc9w",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 11883689
  },
  "DOI_10_1038_s41586_020_2591_3": {
    "driveFileId": "1H7eI26G3th3e0h9_s3hviMnxmF_O4PQ7",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 14039725
  },
  "DOI_10_1038_s41586_021_03436_z": {
    "driveFileId": "1t_mGaW4C_4azpY3cebD_-rabXwoizOxE",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 474222
  },
  "DOI_10_1038_s41597_022_01223_7": {
    "driveFileId": "1FmV_NwgOtJwrJ9l5VwrbOGZEhp_R7c3J",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 191434
  },
  "DOI_10_1038_s41598_026_43863_4": {
    "driveFileId": "1l8nkWNYlotcItnqsdn60UUq1OOhxXIUj",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 3312050
  },
  "DOI_10_1038_s41612_022_00229_7": {
    "driveFileId": "1oSngXtJ-TvECoa3tytcS3suWyldpTMfP",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 937961
  },
  "DOI_10_1038_s43247_020_0001_2": {
    "driveFileId": "1z7kXGc9pYtxs1C9rT1Lhlwos4u_lNJnO",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 1550845
  },
  "DOI_10_1038_s43247_024_01761_5": {
    "driveFileId": "1Df0t9FRizEVgwAlCqgxJoO4B-4cMVnt7",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 593063
  },
  "DOI_10_1038_sdata_2018_206": {
    "driveFileId": "1ntT35QF97CctB_QoOjY6CeOuaDQWUHXY",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 4974908
  },
  "DOI_10_1038_sdata_2018_28": {
    "driveFileId": "1RmA0QZddpfbnixU9LPHz-FUVxLdxca3_",
    "relation": "source-copy",
    "mimeType": "text/plain",
    "size": 115748
  },
  "DOI_10_1073_pnas_0906044106": {
    "driveFileId": "1caWRUE4cd0qkaLlKeMoJG7w0wt58Pyfc",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 1624719
  },
  "DOI_10_1073_pnas_1812883116": {
    "driveFileId": "1ur1PMUCSDGSFey5BLn-3BAClUoyTfkOQ",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 2522860
  },
  "DOI_10_1073_pnas_1904242116": {
    "driveFileId": "1ENSueycY9C02FX9CMklHnmeIwd6vW4DL",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 7998951
  },
  "DOI_10_1088_1748_9326_aae3ec": {
    "driveFileId": "1ePokZdife-Pq9_-TfxHFKBrXSeFdZWNv",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 1492114
  },
  "DOI_10_1088_1748_9326_aaf52c": {
    "driveFileId": "1sEgXWDio_Iflmdc45qU5u6W-LfSr7DUw",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 2443661
  },
  "DOI_10_1098_rspb_2021_2456": {
    "driveFileId": "1OOIM40Dbkyl8hGKQjAR1YGmG5W6k3uOn",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 1456653
  },
  "DOI_10_1111_gcb_15000": {
    "driveFileId": "13MXYOmR5ZcrL_Psybmp-1vnsPH-sg8EG",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 1652393
  },
  "DOI_10_1111_j_2153_3490_1960_tb01300_x": {
    "driveFileId": "1y_H05UjKZKV322ahKmuHUhS_z3Aj0Pf4",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 407138
  },
  "DOI_10_1111_j_2153_3490_1976_tb00701_x": {
    "driveFileId": "1aqaxcQBsA8QSbxXl_iippP7jkF0Rx6kj",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 908244
  },
  "DOI_10_1126_sciadv_1601545": {
    "driveFileId": "1rI6-GQwUoeXcMaQQ5CcKjOI9sw4d7CvL",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 9075218
  },
  "DOI_10_1175_bams_d_25_0104_1": {
    "driveFileId": "17TiYmpARdVB16Jml15BdIM7WVE--vf5u",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 14455395
  },
  "DOI_10_1175_jcli_d_12_00383_1": {
    "driveFileId": "11UBW7qmGDl49D_IGrVIM16IIG18PttM_",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 4765032
  },
  "DOI_10_1175_jcli_d_12_00502_1": {
    "driveFileId": "1rcc3vdn2CrlAYUXL90n_zxWJF1Gi-uZQ",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 3053782
  },
  "DOI_10_1175_jcli_d_18_0094_1": {
    "driveFileId": "17UnE2F5_H4haNjHUsCvXEvrWimgx-aQb",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 2401868
  },
  "DOI_10_1175_jcli_d_18_0143_1": {
    "driveFileId": "1lUO0Ni-Qk0G4u8rMtAxYmZHCrm9Zc_ko",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 3050745
  },
  "DOI_10_1175_jcli_d_19_0998_1": {
    "driveFileId": "1F6tcwiva5l2urBGnl6gNPXZEAb8sXwhM",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 4412590
  },
  "DOI_10_13155_97828": {
    "driveFileId": "1Um5xsTlJ1YmhF6QCzgW64q9ZXDR8xHld",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 4613326
  },
  "DOI_10_15138_9n0h_zh07": {
    "driveFileId": "1eBlxe3QO2BOw1EP-fDvc-XpRdsJjNGwS",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 37265
  },
  "DOI_10_1594_pangaea_884711": {
    "driveFileId": "1r4qbozvjS6TJ9-N7-w1Am0Y8wH-_lcTj",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 59538
  },
  "DOI_10_1594_pangaea_911944": {
    "driveFileId": "15WSGibT2zD3E47OMoAl74dQP6WgpH--g",
    "relation": "source-copy",
    "mimeType": "application/octet-stream",
    "size": 2617
  },
  "DOI_10_2151_sola_2017_030": {
    "driveFileId": "1IohPb6vwsP1t_7IEMmL2SFdLyHTQXhNF",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 680392
  },
  "DOI_10_25921_tn91_wv50": {
    "driveFileId": "1LOrt5ai2DgPR-4RbYHP3ZzDU9fc3SWGD",
    "relation": "source-copy",
    "mimeType": "application/x-gzip",
    "size": 71820
  },
  "DOI_10_25923_cfhv_c239": {
    "driveFileId": "15W_8AI8u4T-oPLLLewHyLTpFD1jvDTWP",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 4249915
  },
  "DOI_10_25923_mmxf_0r86": {
    "driveFileId": "1XexAfXRynr2Zek_Kpd3W3xjwTSNSni5k",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 5271164
  },
  "DOI_10_25923_z885_h264": {
    "driveFileId": "1g_v9NNO_QfWsXTdsnovJ7xk67WbvYStl",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 12098307
  },
  "DOI_10_26008_1912_bco_dmo_3782_8": {
    "driveFileId": "1jFsENUfgonPtddmBEz2XGt7eBWaunzPz",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 111534
  },
  "DOI_10_3133_ofr20181060": {
    "driveFileId": "1XloXA1o2hKPb4s7iyQtMig7YkJgAUgpx",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 1085549
  },
  "DOI_10_3189_2015jog15j017": {
    "driveFileId": "17dGnBMcXJW-a_vH4JdZUKrif-P4cH8PJ",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 4683738
  },
  "DOI_10_3189_s002214300002757x": {
    "driveFileId": "1-jVWQuCK5o6R4B-Quafb5RCAyTKruG43",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 6257444
  },
  "DOI_10_3334_ornldaac_2364": {
    "driveFileId": "1ek0Fo894AkhTOMjwhqbUJkynvFjiDhZm",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 512593
  },
  "DOI_10_3334_ornldaac_2389": {
    "driveFileId": "1Pv7mPAMmjYizicYtPJ8RS45YcRJbAaRk",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 633873
  },
  "DOI_10_3389_fmars_2023_1289931": {
    "driveFileId": "1Y7Mh0TUWOCJcvRQLPjy7EBpdV3cVYvgz",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 31120795
  },
  "DOI_10_3402_tellusa_v10i2_9231": {
    "driveFileId": "1uhjczQRAz5bR3v6fE48VgQvx4RkA1Y7-",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 338889
  },
  "DOI_10_3402_tellusb_v38i2_15083": {
    "driveFileId": "1gkZW_vDr_568CQ6Urk-MrQnFoJsKqrRK",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 1372381
  },
  "DOI_10_4267_2042_36222": {
    "driveFileId": "1OeNDDMZahv-50t5Bkpi3L8jv8NHbVjQL",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 964834
  },
  "DOI_10_48670_moi_00277": {
    "driveFileId": "1tM4f16-H35UF1ESVGurojhasCpEAB_Dm",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 1187846
  },
  "DOI_10_5067_04yyikxw0gjs": {
    "driveFileId": "1F6VyvR3M0gq8yt7KGnxb-O8haXXhfb3S",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 279671
  },
  "DOI_10_5067_2xxgzy3dugnq": {
    "driveFileId": "1-VJaVE7fpFd8FNBprVO14FpChHdqYTiP",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 786357
  },
  "DOI_10_5067_8gq8lzqvl0vl": {
    "driveFileId": "14AJP7vE18awuKt_5dFy27Pu_r4r0akZq",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 498851
  },
  "DOI_10_5067_96jo0kifdas8": {
    "driveFileId": "1Kj1PE63IIuea9z3lWUe7Q-BJKOm_HZ3q",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 335138
  },
  "DOI_10_5067_qozivyv3v9jp": {
    "driveFileId": "1fIe4Vcg4n9rxFhEhGPxmHnP68Ba5QVqt",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 185383
  },
  "DOI_10_5067_txdhdj1jt0cg": {
    "driveFileId": "1HrFR0xjd_QVz4-ZDGlBF4zD7D6lDB1bf",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 849590
  },
  "DOI_10_5067_utav7490fepb": {
    "driveFileId": "16EQg61dmClgIXEHc7BgHbfChZ1MgKxKs",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 1016507
  },
  "DOI_10_5067_viirs_vnp22q2_002": {
    "driveFileId": "1lEgZz9XzLXMnEBUBy2Zh3E3qIvNJQKNL",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 76766
  },
  "DOI_10_5194_acp_24_12925_2024": {
    "driveFileId": "1W6q7v0Ir6XtgU6yrtatPGiU-KIEZfhV2",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 7768772
  },
  "DOI_10_5194_amt_10_2209_2017": {
    "driveFileId": "1mD2uPbWWCa9zFQ5m_oKyMXOB8ZfI51li",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 7456708
  },
  "DOI_10_5194_amt_10_549_2017": {
    "driveFileId": "1ycSQvEWn_AduAr5m1obsrNuqLywdp4iV",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 9282322
  },
  "DOI_10_5194_amt_10_59_2017": {
    "driveFileId": "1i2rdzpBQTV3N50aCObkoK951HRmWC8Kw",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 8346948
  },
  "DOI_10_5194_amt_13_3081_2020": {
    "driveFileId": "1lg6A6hSv23nh06NQnaJjZW34SRqwi3YU",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 12493822
  },
  "DOI_10_5194_amt_14_3015_2021": {
    "driveFileId": "1j31wUUhTofWcfWT1g2mPgdi7_l-OSvD3",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 5057732
  },
  "DOI_10_5194_amt_7_4463_2014": {
    "driveFileId": "1M8Zgt7c1ngyYq7x4wdEL0V4HEw0u6r91",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 6152464
  },
  "DOI_10_5194_amt_7_647_2014": {
    "driveFileId": "1o74cKJSlyzmkJf8nsxlKZrsOuIeq3wjN",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 3313870
  },
  "DOI_10_5194_bg_12_1285_2015": {
    "driveFileId": "1-0DqigCHimJYHt7Hz-_JRf82MPERolK8",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 983447
  },
  "DOI_10_5194_bg_21_5561_2024": {
    "driveFileId": "1XV4tRquf-YoTXDA_kfR3v7JicA-f1qTd",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 7346907
  },
  "DOI_10_5194_cp_10_1983_2014": {
    "driveFileId": "1D4gVMltl2ouP345lZFVv1Lws1olOQLeI",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 2694540
  },
  "DOI_10_5194_cp_8_1649_2012": {
    "driveFileId": "19TABgPdHNqx1Ky1Bfr8hJxiE-oSez7sB",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 5391609
  },
  "DOI_10_5194_essd_11_1189_2019": {
    "driveFileId": "1JjqsGCTGLMESDS37bW0DSYDQKfUS1-So",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 992475
  },
  "DOI_10_5194_essd_12_2853_2020": {
    "driveFileId": "1qzlhYHiNF13mGL0IZmGwem9_rn_3wsUR",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 7891143
  },
  "DOI_10_5194_essd_12_3469_2020": {
    "driveFileId": "1GKiBk7aj4d53BAUIJjHAfZxkyqeK5qCX",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 3892422
  },
  "DOI_10_5194_essd_15_1597_2023": {
    "driveFileId": "1nFqGGXs5sM81G15fWm8ISPEwFjhz6LTq",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 3574079
  },
  "DOI_10_5194_essd_16_121_2024": {
    "driveFileId": "1vrX4mk5k4YoErair5PIJwYAYpE1PMYGQ",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 16381333
  },
  "DOI_10_5194_essd_16_3517_2024": {
    "driveFileId": "1ptUFU0jskHDTL7POwSAa6cUYDF-WKYV0",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 21392556
  },
  "DOI_10_5194_essd_17_1977_2025": {
    "driveFileId": "1wVpkjUuGGjV3qwuFPpKHTY1q51SJtJ1z",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 12458999
  },
  "DOI_10_5194_essd_17_6531_2025": {
    "driveFileId": "1uRErX80hT4-lyS-zt2tdFrYZqT6ma6bo",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 13535787
  },
  "DOI_10_5194_essd_17_719_2025": {
    "driveFileId": "1r-9SSBTvR5QhKgRX-6qqqulIE-VMD7on",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 3020202
  },
  "DOI_10_5194_essd_18_1405_2026": {
    "driveFileId": "1oBiDK80D5A-V9mqU66EvsLPYUfTl3lEb",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 1606816
  },
  "DOI_10_5194_essd_18_1729_2026": {
    "driveFileId": "1SlxQPSG0Egg6a42UJx1OpCcxXXgVFrUN",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 7613677
  },
  "DOI_10_5194_essd_5_71_2013": {
    "driveFileId": "1iL4ngSzkJB4ZD45ZT6SscpXOoQU16DJR",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 12029245
  },
  "DOI_10_5194_essd_6_201_2014": {
    "driveFileId": "19aV6Lq8ge9YHxyQ55Wz4oFs8L4VrL4ub",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 4546577
  },
  "DOI_10_5194_essd_7_117_2015": {
    "driveFileId": "1J-6_cOtu6nJZP_BrsdyFbzFQ4ddbRr0t",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 92829
  },
  "DOI_10_5194_essd_7_137_2015": {
    "driveFileId": "182G2mVt1xaQzG7kM7YwiSH3W182EXv1C",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 1815622
  },
  "DOI_10_5194_essd_7_245_2015": {
    "driveFileId": "1YcvkzwAtIcceKYQyZtcIxRTAzLaHzRu7",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 7266572
  },
  "DOI_10_5194_essd_8_297_2016": {
    "driveFileId": "1ThBvHX5nz-eEuKRwIzuDcrUR4IRjs_ZL",
    "relation": "source-copy",
    "mimeType": "text/plain",
    "size": 130916
  },
  "DOI_10_5194_essd_8_383_2016": {
    "driveFileId": "1IGZEtmY4d4AAUEgrOt_Uauo5oeNWQMPM",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 1529758
  },
  "DOI_10_5194_gmd_15_15_2022": {
    "driveFileId": "19olTmsLOryY3oGlXqx5GIw9D3nBfJf6n",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 2069063
  },
  "DOI_10_5194_hess_15_3033_2011": {
    "driveFileId": "12b2aCJGyCW9MhWi3Z6YY2ZnV9UJIguHD",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 588009
  },
  "DOI_10_5194_os_19_431_2023": {
    "driveFileId": "1sOBMWRAGo2IbwjeTTlTaFVduHX4SP2JY",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 5318316
  },
  "DOI_10_5194_os_20_725_2024": {
    "driveFileId": "1M8MlV_ApqalFyO-j5UEFvTpRIPo-x3yR",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 2660960
  },
  "DOI_10_5194_tc_13_49_2019": {
    "driveFileId": "10OCvqCRvptYy_mQKjEJRQDYHZ4hqaCJj",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 4096720
  },
  "DOI_10_5194_tc_14_1519_2020": {
    "driveFileId": "1wggqQS1osDGx5NT74mUZpFpPVOJHd7xL",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 5555424
  },
  "DOI_10_5194_tc_14_2495_2020": {
    "driveFileId": "19BHkyujaukxtq1CaYf_VvnAr33GZH-3T",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 6985260
  },
  "DOI_10_5194_tc_18_2473_2024": {
    "driveFileId": "15HZ_7earimJakDlkCCzavEuY_VOYr7n_",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 5180759
  },
  "DOI_10_5194_tc_20_3783_2026": {
    "driveFileId": "14QOEN5uuwh8xi1HxCPu4HPBDlnuPrK7T",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 3756413
  },
  "DOI_10_5194_tc_5_219_2011": {
    "driveFileId": "1xYUqV6IGde_zfe29fbXCUpAGx_rpwfkn",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 687503
  },
  "DOI_10_5194_tc_5_271_2011": {
    "driveFileId": "1Hx3hN_Fg9embnGNWvjNYW4X2dIt5VenU",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 7426384
  },
  "DOI_10_5194_tc_7_877_2013": {
    "driveFileId": "1bbPjWYrqM4_GpFKI1MBJPL_sar6kTKOm",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 817284
  },
  "DOI_10_5281_zenodo_20757579": {
    "driveFileId": "1h6K_Qlor3bxz90HpEoMoNw6AgTOh_QXg",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 2165067
  },
  "DOI_10_5281_zenodo_3862995": {
    "driveFileId": "1XI9d5VDB_d0d2Y8M0e8REJQMpHEzavJk",
    "relation": "source-copy",
    "mimeType": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    "size": 271196
  },
  "DOI_10_5285_5675b0be944f45a8af0e7ddbeb47a011": {
    "driveFileId": "1NETWcsiV_k4oe-9RtDdUhCgVhcYJNmOG",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 411777
  },
  "DOI_10_5285_9d9bfc488ec54b1297eca2c9662f9c81": {
    "driveFileId": "1MbPNydEZdhXYPtCuzLiUB9_wSZzEHCrV",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 412179
  },
  "DOI_10_5285_a6fbedd8ee5b472c8e84e55f746c1704": {
    "driveFileId": "1HeHVfMKIS755fq8mp2d1kAy-DPIek-Qa",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 411777
  },
  "DOI_10_5285_d235665772ec4b558e9a89ac85595e71": {
    "driveFileId": "15EZAsXbu2fXXPrf9dML9bxJXl-hq_8un",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 411777
  },
  "DOI_10_5670_oceanog_2009_36": {
    "driveFileId": "1UczFlpMseZ_VgUgBRs-oGAmrviPaBglJ",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 3667793
  },
  "DOI_10_5670_oceanog_2014_16": {
    "driveFileId": "1Uxsv16kSSbXgVLWIzZ4StJ2ZgZibk2Wo",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 2192246
  },
  "DOI_10_6084_m9_figshare_10062239_v1": {
    "driveFileId": "1_F9fbIGGOwEaZY6JYQ9nqZqvhymACE-W",
    "relation": "source-copy",
    "mimeType": "text/csv",
    "size": 148030
  },
  "DOI_10_7265_a98x_0f50": {
    "driveFileId": "1K5fUXpd8fC-I3DI5SM8pr-00lQ_5saxe",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 2010615
  },
  "DOI_10_7265_jj4s_tq79": {
    "driveFileId": "1dpcIZp84Lk3ZUL2G4VGufDauLqPDq3UH",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 3478307
  },
  "DOI_10_7265_n52r3pmc": {
    "driveFileId": "1nHm0P3MNtTF4ZQ04VJOsLDsp3gvuKqqf",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 384597
  },
  "DOI_10_7265_n56d5qxc": {
    "driveFileId": "1q2zz5b3EVlp_r-3dI7lex5k1Dd9-ufwV",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 1049705
  },
  "DOI_10_7289_v5d21vhz": {
    "driveFileId": "1_6FDU-kCFzmDIY0qlPpGVjqVJhle3WK5",
    "relation": "source-copy",
    "mimeType": "text/plain",
    "size": 28567
  },
  "DOI_10_7289_v5n014g9": {
    "driveFileId": "1ANpuEe_4I-_iaKhXWhnEm8twBn6YPoU5",
    "relation": "source-copy",
    "mimeType": "application/x-gzip",
    "size": 3415508
  },
  "WEB_berkeleyearth_org_Data_Overview_Berkeley_Earth_b889a1aa": {
    "driveFileId": "1nez6caSWCZmACjsL8BUMFoI2B3sWMpU8",
    "relation": "related-material",
    "mimeType": "application/pdf",
    "size": 4372792
  },
  "WEB_content_drupal_climate_gov_Climate_Change_Ocean_Heat_Content_a227e082": {
    "driveFileId": "1KckJ-_peoHfKDX8nam8pJGwbSvgDcjOd",
    "relation": "related-material",
    "mimeType": "text/csv",
    "size": 4822
  },
  "WEB_Copernicus_Glaciers_Copernicus_5ae74590": {
    "driveFileId": "1AnOvAuNt7oFuomp65K9yJ8-Lpw3oUBX4",
    "relation": "related-material",
    "mimeType": "application/pdf",
    "size": 481767
  },
  "WEB_Copernicus_globalni_data_CSV_e4635f0c": {
    "driveFileId": "1HK9P8jYOCYA8f9OBRCchWmgKC_YlwitO",
    "relation": "source-copy",
    "mimeType": "text/csv",
    "size": 867329
  },
  "WEB_Copernicus_Graphics_Gallery_Copernicus_4a265eb8": {
    "driveFileId": "1dEpIE6xuh-X_6IC8BrpFUSvf73HoICTl",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 1181312
  },
  "WEB_Copernicus_Licence_to_use_Copernicus_Products_rev_12_4244ad0f": {
    "driveFileId": "12dIljFA3DPjsVp3QpwWpi4NXnqD1XLUO",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 166903
  },
  "WEB_Copernicus_regionalni_data_NetCDF_a6fb7ddf": {
    "driveFileId": "19KuJCuJkqBYlTntojk9i6bBJCaO8sBCA",
    "relation": "source-copy",
    "mimeType": "application/x-netcdf",
    "size": 20763537
  },
  "WEB_Copernicus_Sea_ice_cover_for_March_2026_Copernicus_f75f3111": {
    "driveFileId": "12EaoalGsvo0l1-M1R8Od-uQo8PzT_NVI",
    "relation": "related-material",
    "mimeType": "application/pdf",
    "size": 483634
  },
  "WEB_Copernicus_Sea_ice_cover_for_September_2025_Copernicus_88c9834a": {
    "driveFileId": "1DkiGLm7FPBOXBnJ7Lb4jWnxyJMCMnOU4",
    "relation": "related-material",
    "mimeType": "application/pdf",
    "size": 283430
  },
  "WEB_Copernicus_Sea_level_Copernicus_b943a537": {
    "driveFileId": "1xqLs9ctIRqYIh5yyyLz775oHc1BJl4kD",
    "relation": "related-material",
    "mimeType": "application/pdf",
    "size": 751305
  },
  "WEB_data_jma_go_jp_Japan_Meteorological_Agency_Global_ocean_heat_co_b8363b79": {
    "driveFileId": "1m5VHyq3gbPlQji2SZIl9RYUjohqDSmz3",
    "relation": "related-material",
    "mimeType": "text/plain",
    "size": 4147
  },
  "WEB_Deutscher_Wetterdienst_Wetter_und_Klima_Deutscher_Wetterdienst_Our_serv_386bcd1f": {
    "driveFileId": "1Qo_W7UNM92jFPNNk86QSKiy6fdCsAQqv",
    "relation": "related-material",
    "mimeType": "application/pdf",
    "size": 880113
  },
  "WEB_GitHub_GitHub_fmidev_GlobSnow3_0_1859ddbe": {
    "driveFileId": "1BoAbz7kfnDjIjvKkUsbUX931-4DAuYKt",
    "relation": "source-copy",
    "mimeType": "application/zip",
    "size": 8549
  },
  "WEB_GitHub_GitHub_rhugonnet_ww_tvol_study_Process_global_sc_300ee76a": {
    "driveFileId": "1XR4q8w3p4O57F82DHe9J2baYwLHT_mMd",
    "relation": "source-copy",
    "mimeType": "application/zip",
    "size": 26070303
  },
  "WEB_GitHub_GitHub_thomasfrederikse_sealevelbudget_20c_4d484230": {
    "driveFileId": "1LnFhHi2C22CTho65NvI5MkjlFyf-UpiU",
    "relation": "source-copy",
    "mimeType": "application/zip",
    "size": 439915
  },
  "WEB_imbie_org_imbie_org_e2c3f887": {
    "driveFileId": "1jS-OngR4VIAl1adxOh6KF06_vWki5ZoQ",
    "relation": "related-material",
    "mimeType": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    "size": 105120
  },
  "WEB_Met_Office_uzivatelska_prirucka_HadEX3_6eb86927": {
    "driveFileId": "1hEWdvrhTVbcGjm5wdDaCJ84mFs0SGqfK",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 1307650
  },
  "WEB_NASA_Algorithm_Theoretical_Basis_Document_79780237": {
    "driveFileId": "1WzqXrNwaVpYmttpVdPIBUXIh7amnB5ZS",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 3532839
  },
  "WEB_NASA_Data_GISS_GISS_Surface_Temperature_Analysis_GIST_4f73fdd3": {
    "driveFileId": "1ou2vb00K6-D8id64VTh169MQB_Udqfnv",
    "relation": "source-copy",
    "mimeType": "application/x-gzip",
    "size": 11474455
  },
  "WEB_NASA_Happy_30th_Anniversary_to_TOPEX_Poseidon_Ocean_S_16a22cc4": {
    "driveFileId": "1bMs_sHyNOPtg9BlDsc__i-boMNY4qIVz",
    "relation": "related-material",
    "mimeType": "application/pdf",
    "size": 6475059
  },
  "WEB_NASA_IMERG_Integrated_Multi_satellitE_Retrievals_for_6df632f1": {
    "driveFileId": "1_YQ8daqWQ-C7Pl5-UxeCaTBrCF9__at3",
    "relation": "related-material",
    "mimeType": "application/pdf",
    "size": 2079111
  },
  "WEB_NASA_NASA_Scientific_Visualization_Studio_3D_Water_Va_cbd0352b": {
    "driveFileId": "1BMih2VOdQmGlOjWKaGKzWcKg37xGSnkF",
    "relation": "source-copy",
    "mimeType": "video/mp4",
    "size": 87004134
  },
  "WEB_NASA_NASA_Scientific_Visualization_Studio_Arctic_Sea_8c5c7d01": {
    "driveFileId": "1NRs3uiLrvuDi4hBZaKC0gyDiwtEhUyWe",
    "relation": "source-copy",
    "mimeType": "image/jpeg",
    "size": 150794
  },
  "WEB_NASA_Precipitation_Data_Directory_NASA_Global_Precipi_b0971da5": {
    "driveFileId": "1JqgvEtuloOe_PZxt8kaj7oKpBda8XIz9",
    "relation": "related-material",
    "mimeType": "application/x-gzip",
    "size": 4842227
  },
  "WEB_NASA_Sentinel_6B_Extends_Global_Ocean_Height_Record_N_4996a256": {
    "driveFileId": "1pIKmXJbuWGSoBLXUsMPSslWvQD3UJ3PE",
    "relation": "related-material",
    "mimeType": "application/pdf",
    "size": 2588963
  },
  "WEB_National_Snow_and_Ice_Data_C_IMS_Daily_Northern_Hemisphere_Snow_and_Ice_Analy_254b6e7e": {
    "driveFileId": "1Yoj6rHTH5_XDMYJPM_1sxn5ae2nl2Eat",
    "relation": "related-material",
    "mimeType": "application/pdf",
    "size": 384597
  },
  "WEB_National_Snow_and_Ice_Data_C_uzivatelske_prirucce_Sea_Ice_Index_v4_48d7d043": {
    "driveFileId": "19hm34UFfjHMfqcn68UH4A-S5NdIVRpdA",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 2010615
  },
  "WEB_naturescalendar_woodlandtrus_Nature_s_Calendar_b68eee94": {
    "driveFileId": "11IjkziocLPjqdBKeYbz5rGQJoxLwIvKJ",
    "relation": "related-material",
    "mimeType": "application/pdf",
    "size": 81253
  },
  "WEB_nist_gov_Tuning_into_Weather_Forecasting_NIST_be922613": {
    "driveFileId": "1D6QAD6M5WWYnVwDin80IbciCBjv-dVAK",
    "relation": "related-material",
    "mimeType": "application/pdf",
    "size": 32522291
  },
  "WEB_NOAA_ClimateDashboard_atmospheric_carbon_dioxide_imag_5eb9863d": {
    "driveFileId": "1NDMh7prb67Sodt1Ksw4UK8NjfLocwMuI",
    "relation": "source-copy",
    "mimeType": "image/png",
    "size": 97537
  },
  "WEB_NOAA_Dickson_et_al_2007_prirucka_standardnich_mericic_9661bd2a": {
    "driveFileId": "1Tk9ujvf8k8y5ggOEJKAXdPjZQaVxeuYK",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 5434312
  },
  "WEB_NOAA_Global_Historical_Climatology_Network_daily_GHCN_14491e06": {
    "driveFileId": "1etAQ_-vambYIRMJfzPfPJHjq_DutzWl3",
    "relation": "related-material",
    "mimeType": "application/pdf",
    "size": 104748
  },
  "WEB_NOAA_Global_Ocean_Heat_Content_CDR_f355b1a3": {
    "driveFileId": "1sMBXHsf3X1X6CRJFxaMmINmsnGEuPAnc",
    "relation": "related-material",
    "mimeType": "application/pdf",
    "size": 1084673
  },
  "WEB_NOAA_Integrated_Global_Radiosonde_Archive_IGRA_ab0ea6c1": {
    "driveFileId": "1WqH9WQRA6uK2SxMtND4ra7Am27h8ALbO",
    "relation": "related-material",
    "mimeType": "application/pdf",
    "size": 634165
  },
  "WEB_NOAA_International_Comprehensive_Ocean_Atmosphere_Dat_9d4f6713": {
    "driveFileId": "1KZkseKXdUN7efb0X4DbSuFkaY-4YN3so",
    "relation": "related-material",
    "mimeType": "application/pdf",
    "size": 1611834
  },
  "WEB_NOAA_Mean_Layer_Temperature_NOAA_CDR_743b717d": {
    "driveFileId": "18g_Nr2ErFcKqS-B_M9f0JSHiv6NGVurR",
    "relation": "related-material",
    "mimeType": "application/pdf",
    "size": 1301475
  },
  "WEB_NOAA_NASA_NOAA_prehled_druzic_a566a73a": {
    "driveFileId": "1NsNVQat5L8QEkUu_O2PvZDOOaVyEW_RR",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 1498822
  },
  "WEB_NOAA_NOAA_s_National_Ocean_Service_About_Us_4ba21b52": {
    "driveFileId": "1PuXrL-C0Xo0IonnZ4dVn3J7H0NHb2E46",
    "relation": "related-material",
    "mimeType": "application/pdf",
    "size": 2409138
  },
  "WEB_NOAA_NOAA_WDS_Paleoclimatology_Antarctic_Ice_Cores_Re_1183d28b": {
    "driveFileId": "1LZapLvQ6aNfFteT8LP476v9MJRW0eX6p",
    "relation": "related-material",
    "mimeType": "text/plain",
    "size": 49865
  },
  "WEB_NOAA_Ocean_Carbon_and_Acidification_Data_System_OCADS_23d31f11": {
    "driveFileId": "1RpS0OQPs-87JXcYfXLjpxw5oTVsmbb8R",
    "relation": "source-copy",
    "mimeType": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
    "size": 15227
  },
  "WEB_NOAA_Precipitation_GPCP_Monthly_CDR_9894ca66": {
    "driveFileId": "1Jmx8rPiU2XvdDbaDtBKZl3HbkpoWB6a5",
    "relation": "related-material",
    "mimeType": "application/pdf",
    "size": 764154
  },
  "WEB_NOAA_Radiosonde_Atmospheric_Temperature_Products_for_960a4f75": {
    "driveFileId": "1RjD2pUxOQg3Xoc5hveYtEdS-QMF7FoqS",
    "relation": "source-copy",
    "mimeType": "text/plain",
    "size": 5823
  },
  "WEB_NOAA_Snow_Cover_Extent_Northern_Hemisphere_CDR_85362472": {
    "driveFileId": "1_5ekFttIJz8bHTCIprkOTd7OaaspfCYU",
    "relation": "related-material",
    "mimeType": "application/pdf",
    "size": 2012875
  },
  "WEB_NOAA_State_of_the_Climate_in_2024_tabulka_2_8_4784f00d": {
    "driveFileId": "1UGTAduBG83by7-3sA4L-s6DXjkAMDb_-",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 44832945
  },
  "WEB_NOAA_Trends_in_CO2_NOAA_Global_Monitoring_Laboratory_8f52d95b": {
    "driveFileId": "1j9VYTuNDj3ov8hwCVxPG5J1rS4uyok6a",
    "relation": "related-material",
    "mimeType": "text/csv",
    "size": 38644
  },
  "WEB_NOAA_Trends_in_CO2_NOAA_Global_Monitoring_Laboratory_f1c52261": {
    "driveFileId": "1yVQQ16WnUKQx6gBC8TJ8oCT0vy5HkrEj",
    "relation": "related-material",
    "mimeType": "application/pdf",
    "size": 75313
  },
  "WEB_NOAA_Trends_in_CO2_NOAA_Global_Monitoring_Laboratory_ff9ec92f": {
    "driveFileId": "1P5i0oNNbIGiK-G66sKKeFIuV4-Wvan3n",
    "relation": "related-material",
    "mimeType": "text/csv",
    "size": 24643
  },
  "WEB_NOAA_World_Ocean_Database_3d4b1d70": {
    "driveFileId": "1RWPuPUPvgcmGYfFqwRIhBnznC8F_i_9M",
    "relation": "related-material",
    "mimeType": "application/pdf",
    "size": 12098307
  },
  "WEB_pep725_eu_Dataset_PEP725_5a0c6dbb": {
    "driveFileId": "1YYhW27RItkaEbFnNav-nnGyZBkY4-2rT",
    "relation": "related-material",
    "mimeType": "application/zip",
    "size": 65285
  },
  "WEB_phenocam_nau_edu_PhenoCam_Explorer_V3_173fd14b": {
    "driveFileId": "15QhGQeTxrRrw6B8JTwBl3fQW5jc-0w_x",
    "relation": "related-material",
    "mimeType": "application/pdf",
    "size": 1339091
  },
  "WEB_psc_apl_uw_edu_Polar_Science_Center_raquo_PIOMAS_Data_dbaf6399": {
    "driveFileId": "12TFvRKGLzTTDG0zgyS0FxEjQpspz98tr",
    "relation": "related-material",
    "mimeType": "application/x-gzip",
    "size": 86328
  },
  "WEB_Remote_Sensing_Systems_Remote_Sensing_Systems_25160e34": {
    "driveFileId": "1ador3tfDfLdUG8jB_vpymWKm0cpJ-E4l",
    "relation": "related-material",
    "mimeType": "application/pdf",
    "size": 2628816
  },
  "WEB_Remote_Sensing_Systems_Remote_Sensing_Systems_e8e6fee6": {
    "driveFileId": "1uYwp3-0kHilqD3ADi-fwvUizNpbSHNOc",
    "relation": "related-material",
    "mimeType": "application/pdf",
    "size": 1099410
  },
  "WEB_scrippsco2_ucsd_edu_Mauna_Loa_Observatory_Hawaii_Scripps_CO2_4d2260fe": {
    "driveFileId": "1tpc4iv_7OivnGooangazJDcSYrC84Uro",
    "relation": "source-copy",
    "mimeType": "application/zip",
    "size": 4171757
  },
  "WEB_U_S_Geological_Survey_Grinnell_Glacier_Pair_248d244b": {
    "driveFileId": "1Y0nf2ymw57sT2eFRt7byn6SOuXc8EsJM",
    "relation": "source-copy",
    "mimeType": "image/jpeg",
    "size": 236283
  },
  "WEB_U_S_Geological_Survey_Prirucka_MCD12Q2_v6_1_dbceb14f": {
    "driveFileId": "18b_ahtQc4WPuyd5lXL35ahiZXOojXVJ7",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 558236
  },
  "WEB_World_Glacier_Monitoring_Ser_glosar_UNESCO_a_WGMS_06fc9a79": {
    "driveFileId": "1HdNLAB5kFj4Oj-8Q1IY6LncZCzbN6P2j",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 2861966
  },
  "WEB_World_Glacier_Monitoring_Ser_WGMS_2020_6e490990": {
    "driveFileId": "1kY4kGBVUQfjI7I5-mADzm1eu58niM8Kz",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 4492902
  },
  "WEB_World_Glacier_Monitoring_Ser_WMO_2024_a75c9125": {
    "driveFileId": "1NxqSbtZFNGvJUjXht4PzW3iPaa3Ren84",
    "relation": "source-copy",
    "mimeType": "application/pdf",
    "size": 51154764
  },
  "WEB_World_Meteorological_Organiz_State_of_the_Global_Climate_2025_53cbb3f3": {
    "driveFileId": "1bc6S7Vt7tF12CdOJ2RaHQnWu2zhK-B_L",
    "relation": "related-material",
    "mimeType": "application/pdf",
    "size": 1324091
  }
} as const satisfies Record<string, SourceArchiveFile>;
